#pragma once
#include <glad/glad.h>
#include <windows.h>
#include <GLFW/glfw3.h>
#include <iostream>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include "Shaders.h"
#include "Camera.h"
#include "Sphere.h"
#include "particles.h"
#include "config.h"